### ISSUE TITLE
Feat req: show the corefile that is in use

### ISSUE THREAD

**Issue by Zixim** [bentasker/HomeAssistantAddons#2]
I would find it useful if the Config page (or the log) would cat the corefile that is currently active ?

BTW : huge kudos for doing this !!
This fixes something that should never ever have been broken.

**Comment by bentasker** [comment]
Yeah, I had a similar thought...

I've gone off on a slight tangent at the moment, giving it the ability to stop `supervisor` from auto-updating (my initial bugbear, which led to the DNS stuff).

I figured from a troubleshooting PoV it'd be helpful to have it dump state out before changing anything.

> This fixes something that should never ever have been broken.

Yup. And is still significantly less effort than the arbitrary barriers erected in the pull request that tried to fix this.

**Comment by bentasker** [comment]
OK, this is in, if  currently a tad verbose
```
[15:52:06] INFO: Changes detected - overwriting DNS Config
[15:52:06] INFO: Dumping current /etc/corefile
.:53 {
    log {
        class error
    }
    errors
    loop
    hosts /config/hosts {
        fallthrough
    }
    template ANY AAAA local.hass.io hassio {
        rcode NOERROR
    }
    mdns
    forward . dns://192.168.3.5 dns://127.0.0.1:5553 {
        except local.hass.io
        policy sequential
    }
    cache 600
 }
.:5553 {
    log {
        class error
    }
    errors
    forward . dns://192.168.3.5 {
        except local.hass.io
        
    }
    cache 600
}
[15:52:06] INFO: Changes pushed
[15:52:06] INFO: Dumping current /etc/corefile
.:53 {
    log {
        class error
    }
    errors
    loop
    hosts /config/hosts {
        fallthrough
    }
    template ANY AAAA local.hass.io hassio {
        rcode NOERROR
    }
    mdns
    forward . dns://192.168.3.5  {
        except local.hass.io
        policy sequential
    }
    cache 600
 }
.:5553 {
    log {
        class error
    }
    errors
    forward . dns://192.168.3.5 {
        except local.hass.io
        
    }
    cache 600
}
```

So you get before + after.

Information also gets logged out at add-on startup.

Before I close this, I'll config gate it so that people who don't want the log noise can turn it off

**Comment by bentasker** [comment]
Done - there's now a (default on) option in the addon configuration.
